server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dailybaro?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: smtp.qq.com
    port: 465
    username: 你的QQ邮箱@qq.com
    password: 你的授权码
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.project.model

# 文件上传配置
file:
  upload-dir: /Users/minchi/Desktop/DailyBaro/DailyBaro-api/src/main/resources/uploads/

logging:
  level:
    com.project: debug

wx:
  appId: wx7a9c9b748a323e58
  appSecret: 95c143988801447734046ba89a34eb01

deepseek:
  api-url: https://api.deepseek.com/v1/chat/completions
  api-key: sk-92d68b33753d4ab88721f7abbe4713fa