server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secondhand_transactions?characterEncoding=UTF-8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mvc:
    static-path-pattern: /upload/**
  web:
    resources:
      static-locations:
        - "classpath:/META-INF/resources/"
        - "classpath:/resources/"
        - "classpath:/static/"
        - "classpath:/public/"
        - "file:${file.upload-dir}"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.transactions.model

logging:
  level:
    com.project.transactions: debug

# 文件上传配置
file:
  upload-dir: uploads

# 上传文件大小限制